# test 环境：测试服，按需覆盖 dev 中的地址/端口等（约定见 README-配置约定.md）
server.port=6003
spring.application.name=exchange-api
server.servlet.context-path=/exchange

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bizzan?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

spring.kafka.bootstrap-servers=127.0.0.1:9092
eureka.client.service-url.default-zone=http://127.0.0.1:7421/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}
