# 默认使用 dev 配置（具体项在 dev/application.properties）
spring.profiles.active=dev

eureka.client.service-url.default-zone=http://127.0.0.1:7421/eureka/
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:7421/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}